#include "cryptotech/aes128.h"

#include <array>
#include <cstring>

namespace cryptotech {

namespace {

// GF(2^8) multiplication modulo the AES reduction polynomial
// x^8 + x^4 + x^3 + x + 1 (0x11B), via peasant multiplication.
std::uint8_t gmul(std::uint8_t a, std::uint8_t b) {
    std::uint8_t product = 0;
    for (int i = 0; i < 8; ++i) {
        if (b & 1) {
            product ^= a;
        }
        bool highBitSet = a & 0x80;
        a <<= 1;
        if (highBitSet) {
            a ^= 0x1B;
        }
        b >>= 1;
    }
    return product;
}

// Multiplicative inverse in GF(2^8) via brute-force search (256 elements --
// trivially fast, and avoids implementing the extended Euclidean algorithm
// for a domain this small). 0 is conventionally mapped to 0.
std::uint8_t gInverse(std::uint8_t a) {
    if (a == 0) return 0;
    for (int candidate = 1; candidate < 256; ++candidate) {
        if (gmul(a, static_cast<std::uint8_t>(candidate)) == 1) {
            return static_cast<std::uint8_t>(candidate);
        }
    }
    return 0;  // unreachable for a != 0
}

std::uint8_t rotl8(std::uint8_t b, int shift) {
    return static_cast<std::uint8_t>((b << shift) | (b >> (8 - shift)));
}

// Builds the AES S-box from its mathematical definition rather than a
// hard-coded table: S(x) = Affine(Inverse(x)) in GF(2^8).
std::array<std::uint8_t, 256> buildSbox() {
    std::array<std::uint8_t, 256> sbox{};
    for (int x = 0; x < 256; ++x) {
        std::uint8_t inv = gInverse(static_cast<std::uint8_t>(x));
        std::uint8_t s = inv ^ rotl8(inv, 1) ^ rotl8(inv, 2) ^ rotl8(inv, 3) ^ rotl8(inv, 4) ^ 0x63;
        sbox[static_cast<std::size_t>(x)] = s;
    }
    return sbox;
}

std::array<std::uint8_t, 256> buildInvSbox(const std::array<std::uint8_t, 256>& sbox) {
    std::array<std::uint8_t, 256> inv{};
    for (int x = 0; x < 256; ++x) {
        inv[sbox[static_cast<std::size_t>(x)]] = static_cast<std::uint8_t>(x);
    }
    return inv;
}

// Rcon[i] = x^(i-1) in GF(2^8), generated by repeated doubling rather than
// hard-coded, for the same anti-transcription-error reason as the S-box.
std::array<std::uint8_t, 11> buildRcon() {
    std::array<std::uint8_t, 11> rcon{};
    std::uint8_t value = 0x01;
    rcon[1] = value;
    for (int i = 2; i <= 10; ++i) {
        bool highBitSet = value & 0x80;
        value <<= 1;
        if (highBitSet) value ^= 0x1B;
        rcon[static_cast<std::size_t>(i)] = value;
    }
    return rcon;
}

const std::array<std::uint8_t, 256>& sbox() {
    static const std::array<std::uint8_t, 256> table = buildSbox();
    return table;
}

const std::array<std::uint8_t, 256>& invSbox() {
    static const std::array<std::uint8_t, 256> table = buildInvSbox(sbox());
    return table;
}

const std::array<std::uint8_t, 11>& rcon() {
    static const std::array<std::uint8_t, 11> table = buildRcon();
    return table;
}

void subBytes(std::uint8_t* state) {
    for (int i = 0; i < 16; ++i) state[i] = sbox()[state[i]];
}

void invSubBytes(std::uint8_t* state) {
    for (int i = 0; i < 16; ++i) state[i] = invSbox()[state[i]];
}

// State is column-major: state[r + 4*c] is row r, column c.
void shiftRows(std::uint8_t* s) {
    std::uint8_t t;
    // Row 1: rotate left by 1.
    t = s[1]; s[1] = s[5]; s[5] = s[9]; s[9] = s[13]; s[13] = t;
    // Row 2: rotate left by 2.
    t = s[2]; s[2] = s[10]; s[10] = t; t = s[6]; s[6] = s[14]; s[14] = t;
    // Row 3: rotate left by 3 (= right by 1).
    t = s[15]; s[15] = s[11]; s[11] = s[7]; s[7] = s[3]; s[3] = t;
}

void invShiftRows(std::uint8_t* s) {
    std::uint8_t t;
    // Row 1: rotate right by 1.
    t = s[13]; s[13] = s[9]; s[9] = s[5]; s[5] = s[1]; s[1] = t;
    // Row 2: rotate right by 2.
    t = s[2]; s[2] = s[10]; s[10] = t; t = s[6]; s[6] = s[14]; s[14] = t;
    // Row 3: rotate right by 3 (= left by 1).
    t = s[3]; s[3] = s[7]; s[7] = s[11]; s[11] = s[15]; s[15] = t;
}

void mixColumns(std::uint8_t* s) {
    for (int c = 0; c < 4; ++c) {
        std::uint8_t* col = s + 4 * c;
        std::uint8_t a0 = col[0], a1 = col[1], a2 = col[2], a3 = col[3];
        col[0] = static_cast<std::uint8_t>(gmul(a0, 2) ^ gmul(a1, 3) ^ a2 ^ a3);
        col[1] = static_cast<std::uint8_t>(a0 ^ gmul(a1, 2) ^ gmul(a2, 3) ^ a3);
        col[2] = static_cast<std::uint8_t>(a0 ^ a1 ^ gmul(a2, 2) ^ gmul(a3, 3));
        col[3] = static_cast<std::uint8_t>(gmul(a0, 3) ^ a1 ^ a2 ^ gmul(a3, 2));
    }
}

void invMixColumns(std::uint8_t* s) {
    for (int c = 0; c < 4; ++c) {
        std::uint8_t* col = s + 4 * c;
        std::uint8_t a0 = col[0], a1 = col[1], a2 = col[2], a3 = col[3];
        col[0] = static_cast<std::uint8_t>(gmul(a0, 14) ^ gmul(a1, 11) ^ gmul(a2, 13) ^ gmul(a3, 9));
        col[1] = static_cast<std::uint8_t>(gmul(a0, 9) ^ gmul(a1, 14) ^ gmul(a2, 11) ^ gmul(a3, 13));
        col[2] = static_cast<std::uint8_t>(gmul(a0, 13) ^ gmul(a1, 9) ^ gmul(a2, 14) ^ gmul(a3, 11));
        col[3] = static_cast<std::uint8_t>(gmul(a0, 11) ^ gmul(a1, 13) ^ gmul(a2, 9) ^ gmul(a3, 14));
    }
}

void addRoundKey(std::uint8_t* state, const std::uint8_t* roundKey) {
    for (int i = 0; i < 16; ++i) state[i] ^= roundKey[i];
}

}  // namespace

Aes128::Aes128(const Key& key) { expandKey(key); }

void Aes128::expandKey(const Key& key) {
    // Words are 4-byte chunks; AES-128 has Nk=4, Nr=10 -> 44 words total.
    std::array<std::array<std::uint8_t, 4>, 44> w{};
    for (int i = 0; i < 4; ++i) {
        for (int b = 0; b < 4; ++b) w[static_cast<std::size_t>(i)][b] = key[static_cast<std::size_t>(i * 4 + b)];
    }

    for (int i = 4; i < 44; ++i) {
        std::array<std::uint8_t, 4> temp = w[static_cast<std::size_t>(i - 1)];
        if (i % 4 == 0) {
            // RotWord + SubWord + Rcon.
            std::array<std::uint8_t, 4> rotated = {temp[1], temp[2], temp[3], temp[0]};
            for (auto& byte : rotated) byte = sbox()[byte];
            rotated[0] ^= rcon()[static_cast<std::size_t>(i / 4)];
            temp = rotated;
        }
        for (int b = 0; b < 4; ++b) {
            w[static_cast<std::size_t>(i)][static_cast<std::size_t>(b)] =
                w[static_cast<std::size_t>(i - 4)][static_cast<std::size_t>(b)] ^ temp[static_cast<std::size_t>(b)];
        }
    }

    for (int i = 0; i < 44; ++i) {
        std::memcpy(roundKeys_.data() + i * 4, w[static_cast<std::size_t>(i)].data(), 4);
    }
}

Aes128::Block Aes128::encryptBlock(const Block& plaintext) const {
    std::array<std::uint8_t, 16> state;
    std::memcpy(state.data(), plaintext.data(), 16);

    addRoundKey(state.data(), roundKeys_.data());
    for (int round = 1; round < kRounds; ++round) {
        subBytes(state.data());
        shiftRows(state.data());
        mixColumns(state.data());
        addRoundKey(state.data(), roundKeys_.data() + round * 16);
    }
    subBytes(state.data());
    shiftRows(state.data());
    addRoundKey(state.data(), roundKeys_.data() + kRounds * 16);

    Block out;
    std::memcpy(out.data(), state.data(), 16);
    return out;
}

Aes128::Block Aes128::decryptBlock(const Block& ciphertext) const {
    std::array<std::uint8_t, 16> state;
    std::memcpy(state.data(), ciphertext.data(), 16);

    addRoundKey(state.data(), roundKeys_.data() + kRounds * 16);
    for (int round = kRounds - 1; round > 0; --round) {
        invShiftRows(state.data());
        invSubBytes(state.data());
        addRoundKey(state.data(), roundKeys_.data() + round * 16);
        invMixColumns(state.data());
    }
    invShiftRows(state.data());
    invSubBytes(state.data());
    addRoundKey(state.data(), roundKeys_.data());

    Block out;
    std::memcpy(out.data(), state.data(), 16);
    return out;
}

}  // namespace cryptotech
