#include "cryptotech/aes128.h"

#include <array>
#include <cstring>

namespace cryptotech {

namespace {

// GF(2^8) multiplication modulo the AES reduction polynomial
// x^8 + x^4 + x^3 + x + 1 (0x11B), via peasant multiplication.
std::uint8_t Gmul(std::uint8_t a, std::uint8_t b) {
    std::uint8_t product = 0;
    for (int i = 0; i < 8; ++i) {
        if (b & 1) {
            product ^= a;
        }
        bool high_bit_set = a & 0x80;
        a <<= 1;
        if (high_bit_set) {
            a ^= 0x1B;
        }
        b >>= 1;
    }
    return product;
}

// Multiplicative inverse in GF(2^8) via brute-force search (256 elements --
// trivially fast, and avoids implementing the extended Euclidean algorithm
// for a domain this small). 0 is conventionally mapped to 0.
std::uint8_t GInverse(std::uint8_t a) {
    if (a == 0) return 0;
    for (int candidate = 1; candidate < 256; ++candidate) {
        if (Gmul(a, static_cast<std::uint8_t>(candidate)) == 1) {
            return static_cast<std::uint8_t>(candidate);
        }
    }
    return 0;  // unreachable for a != 0
}

std::uint8_t Rotl8(std::uint8_t b, int shift) {
    return static_cast<std::uint8_t>((b << shift) | (b >> (8 - shift)));
}

// Builds the AES S-box from its mathematical definition rather than a
// hard-coded table: S(x) = Affine(Inverse(x)) in GF(2^8).
std::array<std::uint8_t, 256> BuildSbox() {
    std::array<std::uint8_t, 256> sbox{};
    for (int x = 0; x < 256; ++x) {
        std::uint8_t inv = GInverse(static_cast<std::uint8_t>(x));
        std::uint8_t s = inv ^ Rotl8(inv, 1) ^ Rotl8(inv, 2) ^ Rotl8(inv, 3) ^ Rotl8(inv, 4) ^ 0x63;
        sbox[static_cast<std::size_t>(x)] = s;
    }
    return sbox;
}

std::array<std::uint8_t, 256> BuildInvSbox(const std::array<std::uint8_t, 256>& sbox) {
    std::array<std::uint8_t, 256> inv{};
    for (int x = 0; x < 256; ++x) {
        inv[sbox[static_cast<std::size_t>(x)]] = static_cast<std::uint8_t>(x);
    }
    return inv;
}

// Rcon[i] = x^(i-1) in GF(2^8), generated by repeated doubling rather than
// hard-coded, for the same anti-transcription-error reason as the S-box.
std::array<std::uint8_t, 11> BuildRcon() {
    std::array<std::uint8_t, 11> rcon{};
    std::uint8_t value = 0x01;
    rcon[1] = value;
    for (int i = 2; i <= 10; ++i) {
        bool high_bit_set = value & 0x80;
        value <<= 1;
        if (high_bit_set) value ^= 0x1B;
        rcon[static_cast<std::size_t>(i)] = value;
    }
    return rcon;
}

const std::array<std::uint8_t, 256>& Sbox() {
    static const std::array<std::uint8_t, 256> kTable = BuildSbox();
    return kTable;
}

const std::array<std::uint8_t, 256>& InvSbox() {
    static const std::array<std::uint8_t, 256> kTable = BuildInvSbox(Sbox());
    return kTable;
}

const std::array<std::uint8_t, 11>& Rcon() {
    static const std::array<std::uint8_t, 11> kTable = BuildRcon();
    return kTable;
}

void SubBytes(std::uint8_t* state) {
    for (int i = 0; i < 16; ++i) state[i] = Sbox()[state[i]];
}

void InvSubBytes(std::uint8_t* state) {
    for (int i = 0; i < 16; ++i) state[i] = InvSbox()[state[i]];
}

// State is column-major: state[r + 4*c] is row r, column c.
void ShiftRows(std::uint8_t* s) {
    std::uint8_t t;
    // Row 1: rotate left by 1.
    t = s[1]; s[1] = s[5]; s[5] = s[9]; s[9] = s[13]; s[13] = t;
    // Row 2: rotate left by 2.
    t = s[2]; s[2] = s[10]; s[10] = t; t = s[6]; s[6] = s[14]; s[14] = t;
    // Row 3: rotate left by 3 (= right by 1).
    t = s[15]; s[15] = s[11]; s[11] = s[7]; s[7] = s[3]; s[3] = t;
}

void InvShiftRows(std::uint8_t* s) {
    std::uint8_t t;
    // Row 1: rotate right by 1.
    t = s[13]; s[13] = s[9]; s[9] = s[5]; s[5] = s[1]; s[1] = t;
    // Row 2: rotate right by 2.
    t = s[2]; s[2] = s[10]; s[10] = t; t = s[6]; s[6] = s[14]; s[14] = t;
    // Row 3: rotate right by 3 (= left by 1).
    t = s[3]; s[3] = s[7]; s[7] = s[11]; s[11] = s[15]; s[15] = t;
}

void MixColumns(std::uint8_t* s) {
    for (int c = 0; c < 4; ++c) {
        std::uint8_t* col = s + 4 * c;
        std::uint8_t a0 = col[0], a1 = col[1], a2 = col[2], a3 = col[3];
        col[0] = static_cast<std::uint8_t>(Gmul(a0, 2) ^ Gmul(a1, 3) ^ a2 ^ a3);
        col[1] = static_cast<std::uint8_t>(a0 ^ Gmul(a1, 2) ^ Gmul(a2, 3) ^ a3);
        col[2] = static_cast<std::uint8_t>(a0 ^ a1 ^ Gmul(a2, 2) ^ Gmul(a3, 3));
        col[3] = static_cast<std::uint8_t>(Gmul(a0, 3) ^ a1 ^ a2 ^ Gmul(a3, 2));
    }
}

void InvMixColumns(std::uint8_t* s) {
    for (int c = 0; c < 4; ++c) {
        std::uint8_t* col = s + 4 * c;
        std::uint8_t a0 = col[0], a1 = col[1], a2 = col[2], a3 = col[3];
        col[0] = static_cast<std::uint8_t>(Gmul(a0, 14) ^ Gmul(a1, 11) ^ Gmul(a2, 13) ^ Gmul(a3, 9));
        col[1] = static_cast<std::uint8_t>(Gmul(a0, 9) ^ Gmul(a1, 14) ^ Gmul(a2, 11) ^ Gmul(a3, 13));
        col[2] = static_cast<std::uint8_t>(Gmul(a0, 13) ^ Gmul(a1, 9) ^ Gmul(a2, 14) ^ Gmul(a3, 11));
        col[3] = static_cast<std::uint8_t>(Gmul(a0, 11) ^ Gmul(a1, 13) ^ Gmul(a2, 9) ^ Gmul(a3, 14));
    }
}

void AddRoundKey(std::uint8_t* state, const std::uint8_t* round_key) {
    for (int i = 0; i < 16; ++i) state[i] ^= round_key[i];
}

}  // namespace

Aes128::Aes128(const Key& key) { ExpandKey(key); }

void Aes128::ExpandKey(const Key& key) {
    // Words are 4-byte chunks; AES-128 has Nk=4, Nr=10 -> 44 words total.
    std::array<std::array<std::uint8_t, 4>, 44> w{};
    for (int i = 0; i < 4; ++i) {
        for (int b = 0; b < 4; ++b) w[static_cast<std::size_t>(i)][b] = key[static_cast<std::size_t>(i * 4 + b)];
    }

    for (int i = 4; i < 44; ++i) {
        std::array<std::uint8_t, 4> temp = w[static_cast<std::size_t>(i - 1)];
        if (i % 4 == 0) {
            // RotWord + SubWord + Rcon.
            std::array<std::uint8_t, 4> rotated = {temp[1], temp[2], temp[3], temp[0]};
            for (auto& byte : rotated) byte = Sbox()[byte];
            rotated[0] ^= Rcon()[static_cast<std::size_t>(i / 4)];
            temp = rotated;
        }
        for (int b = 0; b < 4; ++b) {
            w[static_cast<std::size_t>(i)][static_cast<std::size_t>(b)] =
                w[static_cast<std::size_t>(i - 4)][static_cast<std::size_t>(b)] ^ temp[static_cast<std::size_t>(b)];
        }
    }

    for (int i = 0; i < 44; ++i) {
        std::memcpy(round_keys_.data() + i * 4, w[static_cast<std::size_t>(i)].data(), 4);
    }
}

Aes128::Block Aes128::EncryptBlock(const Block& plaintext) const {
    std::array<std::uint8_t, 16> state;
    std::memcpy(state.data(), plaintext.data(), 16);

    AddRoundKey(state.data(), round_keys_.data());
    for (int round = 1; round < kRounds; ++round) {
        SubBytes(state.data());
        ShiftRows(state.data());
        MixColumns(state.data());
        AddRoundKey(state.data(), round_keys_.data() + round * 16);
    }
    SubBytes(state.data());
    ShiftRows(state.data());
    AddRoundKey(state.data(), round_keys_.data() + kRounds * 16);

    Block out;
    std::memcpy(out.data(), state.data(), 16);
    return out;
}

Aes128::Block Aes128::DecryptBlock(const Block& ciphertext) const {
    std::array<std::uint8_t, 16> state;
    std::memcpy(state.data(), ciphertext.data(), 16);

    AddRoundKey(state.data(), round_keys_.data() + kRounds * 16);
    for (int round = kRounds - 1; round > 0; --round) {
        InvShiftRows(state.data());
        InvSubBytes(state.data());
        AddRoundKey(state.data(), round_keys_.data() + round * 16);
        InvMixColumns(state.data());
    }
    InvShiftRows(state.data());
    InvSubBytes(state.data());
    AddRoundKey(state.data(), round_keys_.data());

    Block out;
    std::memcpy(out.data(), state.data(), 16);
    return out;
}

}  // namespace cryptotech
